----STANDARD QUERY 1: RAW DATA FOR A GIVEN TIMESTEP

USE [CLIMATE_DATA_V1]
GO

DBCC DROPCLEANBUFFERS
GO

SET STATISTICS IO ON
SET STATISTICS TIME ON
GO

SELECT [Latitude], [Longitude], [E0]
FROM [OBT].[V4]
WHERE [Year] = 1930 AND [Month] = 6 AND [Day] = 15 -- SPECIFY TIMESTEP HERE
ORDER BY SpaceID

SET STATISTICS IO OFF
SET STATISTICS TIME OFF
GO