---- STANDARD QUERY 4: LONG-TERM AVERAGE (Spatial)

USE [CLIMATE_DATA_V1]
GO

DBCC DROPCLEANBUFFERS
GO

SET STATISTICS IO ON
SET STATISTICS TIME ON
GO


SELECT [Latitude], [Longitude], [Bvg_E0]
FROM 
	(SELECT  [SpaceID], AVG([Avg_E0]) AS Bvg_E0
	FROM [OBT].[ANNUAL_V1]
	WHERE [Year] = 1930  -- DEFINE TIME PERIOD HERE
	GROUP BY [SpaceID]) AS S
	JOIN 
	(SELECT DISTINCT [SpaceID], [Longitude], [Latitude] 	FROM [DIMENSION].[SPACE]) AS dim
	ON dim.[SpaceID] = S.[SpaceID] 
ORDER BY dim.[SpaceID]


SET STATISTICS IO OFF
SET STATISTICS TIME OFF
GO

SELECT * FROM [OBT].[ANNUAL_V1] ORDER BY [SpaceID], [Year]