---- STANDARD QUERY 2: ABSOLUTE MAXIMUM OVER A SPECIFIED YEAR

USE [CLIMATE_DATA_V1]
GO

DBCC DROPCLEANBUFFERS
GO

SET STATISTICS IO ON
SET STATISTICS TIME ON
GO

;WITH Time_Range AS (
	SELECT * 
	FROM [DW4].[OBT]
	WHERE [Year] = 1930 -- SPECIFY TEMPORAL RANGE HERE
	)

SELECT [Latitude], [Longitude], [Max_E0]
FROM 
	(SELECT  [SpaceID], MAX([E0]) AS Max_E0
	FROM Time_Range
	GROUP BY [SpaceID]) AS S
	JOIN 
	[DIMENSION].[SPACE_OUTPUT] AS dim
	ON dim.[SpaceID] = S.[SpaceID] 
ORDER BY dim.[SpaceID]

SET STATISTICS IO OFF
SET STATISTICS TIME OFF
GO