---- STANDARD QUERY 2: ABSOLUTE MAXIMUM OVER A SPECIFIED YEAR
USE [CLIMATE_DATA_V1]
GO

DBCC DROPCLEANBUFFERS
GO

SET STATISTICS IO ON
SET STATISTICS TIME ON
GO

SELECT [Latitude], [Longitude], MAX([E0]) AS Max_E0
FROM (
		(SELECT * FROM [DW3].[Time] WHERE [Year] = 1930) AS T  -- SPECIFY TEMPORAL RANGE HERE
		LEFT JOIN 
		[DW3].[FACT] AS F
		ON [T].[TimeID] = [F].[TimeID]
		LEFT JOIN 
		[DW3].[Space] AS S
		ON [S].[SpaceID] = [F].[SpaceID]
		)
GROUP BY [F].[SpaceID], [Latitude], [Longitude]
ORDER BY [F].[SpaceID]


SET STATISTICS IO OFF
SET STATISTICS TIME OFF
GO