----STANDARD QUERY 1: RAW DATA FOR A GIVEN TIMESTEP
USE [CLIMATE_DATA_V1]
GO

DBCC DROPCLEANBUFFERS
GO

SET STATISTICS IO ON
SET STATISTICS TIME ON
GO

SELECT [Latitude], [Longitude], [E0]
FROM (
		(SELECT * FROM [DW3].[Time] WHERE [Year] = 1930 AND [Month] = 6 AND [Day] = 15) AS T  -- SPECIFY TIMESTEP HERE
		LEFT JOIN 
		[DW3].[FACT] AS F
		ON [T].[TimeID] = [F].[TimeID]
		LEFT JOIN 
		[DW3].[Space] AS S
		ON [S].[SpaceID] = [F].[SpaceID]
		)
ORDER BY [F].[SpaceID]

SET STATISTICS IO OFF
SET STATISTICS TIME OFF
GO