USE CLIMATE_DATA_V1
GO

--CREATE SCHEMA DW9

-- GRID TABLE
DROP TABLE IF EXISTS [DW9].[GRID]

CREATE TABLE  [DW9].[GRID](
		[GridID] INT,
		[Latitude] DECIMAL(5,2),
		[Longitude] DECIMAL(5,2),
		INDEX COLUMNSTORE_GRID CLUSTERED COLUMNSTORE
        );
BULK INSERT [DW9].[GRID]
FROM 'D:\CSIRO\STAR-SCHEMA V2\DIMENSION_GRID.csv'
WITH( 
    FIRSTROW = 2, 
    FIELDTERMINATOR = ',', 
    ROWTERMINATOR = '\n', 
    KEEPNULLS 
    )
GO

-- TIME TABLE: should be small enough that it doesn't actually use columnstore
DROP TABLE IF EXISTS [DW9].[TIME]
CREATE TABLE  [DW9].[TIME](
		[DateID] SMALLINT,
		[DateTime] SMALLDATETIME,
		--[Year] SMALLINT,
		--[Month] TINYINT,
		--[Day] TINYINT,
		INDEX COLUMNSTORE_TIME CLUSTERED COLUMNSTORE
        );
BULK INSERT [DW9].[TIME]
FROM 'D:\CSIRO\STAR-SCHEMA V2\DIMENSION_TIME1.csv'
WITH( 
    FIRSTROW = 2, 
    FIELDTERMINATOR = ',', 
    ROWTERMINATOR = '\n', 
    KEEPNULLS 
    )
GO


DROP TABLE IF EXISTS [DW9].[OBT]
DROP TABLE IF EXISTS [DW9].[FACT]
CREATE TABLE  [DW9].[FACT](
		[ID] BIGINT IDENTITY(1,1), -- 
		[DateID] SMALLINT,
		[GridID] INT, 
		[E0] FLOAT,
		INDEX DW9_COLUMNSTORE_FACT CLUSTERED COLUMNSTORE
        );

DROP VIEW IF EXISTS [DW9_FACT]
GO
CREATE VIEW DW9_FACT ([DateID], [GridID], [E0]) AS
	SELECT [DateID], [GridID], [E0] FROM [DW9].[FACT];
GO


DBCC SHRINKFILE (N'CLIMATE_DATA_V1_log' , 0, TRUNCATEONLY)
GO
DECLARE 
		@Year INT,
		@YearStart INT,
		@YearEnd INT,
		@YearIncrement INT,
		@ProgressPercent DECIMAL(5,2),
		@FilePath NVARCHAR(30),
		@FileName NVARCHAR(20),
		@Bulk_Insert_Command NVARCHAR(200),
		@CreateView_LoadingTable NVARCHAR(200);

SET @YearStart	= 1911;
SET @YearEnd	= 1950;
SET @Year		= @YearStart;
SET @YearIncrement = 1;
SET @FilePath = 'D:\CSIRO\STAR-SCHEMA V1\'

WHILE (@Year <= @YearEnd)
BEGIN;
	SET @FileName = N'FACT ' + CAST(@Year AS NVARCHAR(4)) + '.csv';

	SET @Bulk_Insert_Command = '
	BULK INSERT [DW9_OBT]
	FROM ''' + @FilePath + @FileName + '''
	WITH( 
		FIRSTROW = 2, 
		FIELDTERMINATOR = '','', 
		ROWTERMINATOR = ''\n'',
		KEEPNULLS 
		)'

	PRINT  CAST(CURRENT_TIMESTAMP AS NVARCHAR(40)) + N': LOADING FILE "' + @FileName + '"'
	EXEC(@Bulk_Insert_Command)

	CHECKPOINT
	DBCC SHRINKFILE (N'CLIMATE_DATA_V1_log' , 0, TRUNCATEONLY)

	SET @Year = @Year + @YearIncrement;
	SET @ProgressPercent = 100 * (CAST(@Year - @YearStart AS FLOAT) / CAST(@YearEnd - @YearStart + 1 AS FLOAT));
	PRINT  CAST(CURRENT_TIMESTAMP AS NVARCHAR(40)) + N': ' + CAST(@ProgressPercent AS NVARCHAR(6)) +'% COMPLETE'
END

DROP VIEW IF EXISTS DW9_OBT




























-- MODIFYING THE STRUCTURE OF DW3 TO ADD SPLIT INTEGER DATES, RATHER THAN RE-INGESTING. -
-- OUTCOME: didn't work. first column took 3 hours then blew out the transaction log

--ALTER TABLE [DW3].[OBT]
--DROP COLUMN [Year], [Month], [Day]

----ALTER TABLE [DW3].[OBT]
----ADD [Year] SMALLINT NULL,
----	[Month] TINYINT NULL,
----	[Day] TINYINT NULL;

--DBCC SHRINKFILE (N'CLIMATE_DATA_V1_log' , 0, TRUNCATEONLY)

--UPDATE [DW3].[OBT]
--SET [Year] =	YEAR([DateTime]);
--CHECKPOINT
--DBCC SHRINKFILE (N'CLIMATE_DATA_V1_log' , 0, TRUNCATEONLY)

--UPDATE [DW3].[OBT]
--SET [Month] =	MONTH([DateTime]);
--CHECKPOINT
--DBCC SHRINKFILE (N'CLIMATE_DATA_V1_log' , 0, TRUNCATEONLY)

--UPDATE [DW3].[OBT]
--SET [Day] =		DAY([DateTime]);
--CHECKPOINT
--DBCC SHRINKFILE (N'CLIMATE_DATA_V1_log' , 0, TRUNCATEONLY)

--ALTER TABLE [DW3].[OBT]
--DROP COLUMN [DateTime]
--CHECKPOINT
--DBCC SHRINKFILE (N'CLIMATE_DATA_V1_log' , 0, TRUNCATEONLY)

---- NEED TO FIGURE OUT WHAT TO DO ABOUT THE INDEX

--SELECT TOP(100) * FROM [DW3].[OBT]