-- -- ADDING AN INDEXED VIEW ON [DW6]
-- -- NOT INGESTING THE TABLE ALL OVER AGAIN.

--CREATE SCHEMA [DW8]

DROP INDEX IF EXISTS [DW7_POC_INDEX] ON [DW6].[OBT]

CHECKPOINT
DBCC SHRINKFILE (N'CLIMATE_DATA_V1_log' , 0, TRUNCATEONLY)
GO

SET ANSI_NULLS,
	ANSI_PADDING,
	ANSI_WARNINGS,
	ARITHABORT,
	CONCAT_NULL_YIELDS_NULL,
	QUOTED_IDENTIFIER ON;
SET NUMERIC_ROUNDABORT OFF
GO
-- As advised by https://docs.microsoft.com/en-us/sql/relational-databases/views/create-indexed-views?view=sql-server-ver15

PRINT 'HERE'
GO

DROP VIEW IF EXISTS [DW8].[VOBT]
GO

CREATE VIEW [DW8].[VOBT] ([Year], [Month], [Day], [GridID], [E0]) 
WITH SCHEMABINDING
AS
	SELECT [Year], [Month], [Day], [GridID], [E0] FROM [DW6].[OBT]
GO

DROP INDEX IF EXISTS [DW8_POC_INDEX] ON [DW8].[VOBT]
CREATE UNIQUE CLUSTERED INDEX [DW8_POC_INDEX]
ON [DW8].[VOBT] ([GridID], [E0], [Year], [Month], [Day]) 
--WITH (IGNORE_DUP_KEY = OFF);

CHECKPOINT
DBCC SHRINKFILE (N'CLIMATE_DATA_V1_log' , 0, TRUNCATEONLY)

--SELECT COLUMNPROPERTY(OBJECT_ID('[DW8].[VOBT]'), 'Year', 'IsDeterministic') AS DET1
--SELECT COLUMNPROPERTY(OBJECT_ID('[DW8].[VOBT]'), 'Month', 'IsDeterministic') AS DET2
--SELECT COLUMNPROPERTY(OBJECT_ID('[DW8].[VOBT]'), 'Day', 'IsDeterministic') AS DET3
--SELECT COLUMNPROPERTY(OBJECT_ID('[DW8].[VOBT]'), 'GridID', 'IsDeterministic') AS DET4
--SELECT COLUMNPROPERTY(OBJECT_ID('[DW8].[VOBT]'), 'E0', 'IsDeterministic') AS DET5
--SELECT OBJECT_ID('[DW6].[OBT]')

EXEC sys.sp_spaceused @objname = N'CLIMATE_DATA_V1.DW8.VOBT'