-- -- ADDING AN INDEXED VIEW ON [DW6]
-- -- NOT INGESTING THE TABLE ALL OVER AGAIN.

--CREATE SCHEMA [DW8]

DROP INDEX IF EXISTS [DW7_POC_INDEX] ON [DW6].[OBT]

CHECKPOINT
DBCC SHRINKFILE (N'CLIMATE_DATA_V1_log' , 0, TRUNCATEONLY)
GO

SET ANSI_NULLS,
	ANSI_PADDING,
	ANSI_WARNINGS,
	ARITHABORT,
	CONCAT_NULL_YIELDS_NULL,
	QUOTED_IDENTIFIER ON;
SET NUMERIC_ROUNDABORT OFF
GO
-- As advised by https://docs.microsoft.com/en-us/sql/relational-databases/views/create-indexed-views?view=sql-server-ver15

CREATE VIEW [DW8].[OBT] ([Year], [Month], [Day], [GridID]) 
WITH SCHEMABINDING
AS
	SELECT [Year], [Month], [Day], [GridID] FROM [DW6].[OBT]
GO

CREATE UNIQUE CLUSTERED INDEX [DW8_POC_INDEX]
ON [DW8_OBT] ([GridID], [E0]) INCLUDE ([Year], [Month], [Day])

CHECKPOINT
DBCC SHRINKFILE (N'CLIMATE_DATA_V1_log' , 0, TRUNCATEONLY)

