USE CLIMATE_DATA_V1
GO

--CREATE SCHEMA DW4
--DROP TABLE IF EXISTS [DW4].[OBT]

--CREATE TABLE  [DW4].[OBT](
--		[Year] SMALLINT, 
--		[Month] SMALLINT, 
--		[Day] SMALLINT, 
--		[SpaceID] INT, 
--		[Latitude] DECIMAL(5,2), 
--		[Longitude] DECIMAL(5,2),
--		[E0] FLOAT,
--		INDEX COLUMNSTORE_DW4_OBT  CLUSTERED COLUMNSTORE 
--        );

--INSERT INTO [DW4].[OBT]
--SELECT [Year], [Month], [Day], [SpaceID], [Longitude], [Latitude], [E0]
--FROM [OBT].[V4]

-- DW 2.1
--DROP INDEX IF EXISTS ROWSTORE_POC_DW4_V1 ON [DW4].[OBT]
--CREATE NONCLUSTERED INDEX ROWSTORE_POC_DW4_V1
--	ON [DW4].[OBT] ([Year] ASC, [Month] ASC, [Day] ASC, [SpaceID] ASC)
--    INCLUDE([E0]);

--DROP INDEX IF EXISTS ROWSTORE_POC_DW4_V2 ON [DW4].[OBT]
--CREATE NONCLUSTERED INDEX ROWSTORE_POC_DW4_V2
--	ON [DW4].[OBT] ([Year] ASC, [Month] ASC, [SpaceID] ASC)
--    INCLUDE([E0]);

DROP INDEX IF EXISTS ROWSTORE_POC_DW4_V3 ON [DW4].[OBT]
CREATE NONCLUSTERED INDEX ROWSTORE_POC_DW4_V3
	ON [DW4].[OBT] ([Year] ASC, [SpaceID] ASC)
    INCLUDE([E0]);




-- DW 2.3
--CREATE NONCLUSTERED COLUMNSTORE INDEX NC_COLUMNSTORE_POC_DW6_V1
--	ON [DW6].[OBT] ([Year] ASC, [Month] ASC, [Day] ASC, [SpaceID] ASC)
--    INCLUDE([E0]);

--CREATE NONCLUSTERED COLUMNSTORE INDEX NC_COLUMNSTORE_POC_DW6_V1
--	ON [DW6].[OBT] ([Year] ASC, [Month] ASC, [SpaceID] ASC)
--    INCLUDE([E0]);

-- DW 2.4


